site_name: Uptime Badge Demo
site_description: Demo site for the MkDocs Kuma Uptime Badge Plugin

plugins:
  - search
  - kuma-uptime-badge:
      base_url: https://demo.uptime-kuma.example.com

nav:
  - Home: index.md
  - Examples: examples.md

theme:
  name: material
